=== ClimateMind/climatemind-backend/app/personal_values/static/value_descriptions.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Values description",
  "type": "object",
  "$defs": {
    "value_description": {
      "title": "Single value description",
      "type": "object",
      "required": [
        "id",
        "name",
        "description",
        "shortDescription",
        "shortDescriptionShared"
      ],
      "properties": {
        "id": {
          "title": "Personal Value Key",
          "type": "string",
          "enum": [
            "hedonism",
            "tradition",
            "benevolence",
            "conformity",
            "stimulation",
            "security",
            "achievement",
            "universalism",
            "power",
            "self_direction"
          ]
        },
        "name": {
          "title": "Personal Value Name",
          "type": "string",
          "enum": [
            "hedonism",
            "tradition",
            "benevolence",
            "conformity",
            "stimulation",
            "security",
            "achievement",
            "universalism",
            "power",
            "self direction"
          ]
        },
        "description": {
          "title": "Description",
          "type": "string"
        },
        "shortDescription": {
          "title": "Short Description",
          "type": "string"
        },
        "shortDescriptionShared": {
          "title": "Short Description Shared",
          "type": "string"
        }
      }
    }
  },
  "required": [
    "conformity",
    "tradition",
    "universalism",
    "benevolence",
    "self_direction",
    "stimulation",
    "hedonism",
    "achievement",
    "power",
    "security"
  ],
  "properties": {
    "conformity": {
      "$ref": "#/$defs/value_description"
    },
    "tradition": {
      "$ref": "#/$defs/value_description"
    },
    "security": {
      "$ref": "#/$defs/value_description"
    },
    "power": {
      "$ref": "#/$defs/value_description"
    },
    "achievement": {
      "$ref": "#/$defs/value_description"
    },
    "hedonism": {
      "$ref": "#/$defs/value_description"
    },
    "stimulation": {
      "$ref": "#/$defs/value_description"
    },
    "self_direction": {
      "$ref": "#/$defs/value_description"
    },
    "benevolence": {
      "$ref": "#/$defs/value_description"
    },
    "universalism": {
      "$ref": "#/$defs/value_description"
    }
  },
  "x-internal": true
}

=== ClimateMind/climatemind-backend/app/personal_values/static/value_descriptions.json
{
  "conformity": {
    "id": "conformity",
    "name": "conformity",
    "description": "The idea of upsetting others or disrupting the status quo likely fills you with dread, so you work hard to bring self-discipline, responsibility and politeness to the table.",
    "descriptionShared": "The idea of upsetting others or disrupting the status quo likely fills each of you with dread, so you both work hard to bring self-discipline, responsibility and politeness to the table.",
    "shortDescription": "Rule breaker? Far from it. In fact, you love nothing more than sticking by the rules and conforming to social norms.",
    "shortDescriptionShared": "Rule breakers? Far from it. In fact, you both love nothing more than sticking by the rules and conforming to social norms."
  },
  "tradition": {
    "id": "tradition",
    "name": "tradition",
    "description": "As a person, you care deeply about humility and accepting your place in the world. Most likely you are a religious person and find following your faith to be very important.",
    "descriptionShared": "As a person, you both care deeply about humility and accepting your place in the world. Most likely both of you are religious and find following your faith to be very important.",
    "shortDescription": "You value protecting the traditions of your family, community, and/or culture. You likely take pride in this commitment.",
    "shortDescriptionShared": "You both value protecting the traditions of your family, community, and/or culture. You both likely take pride in this commitment."
  },
  "universalism": {
    "id": "universalism",
    "name": "universalism",
    "description": "Broadminded and selfless, you likely focus on bolstering social justice and equality so that the world is more fair and peaceful for all.",
    "descriptionShared": "Broadminded and selfless, you both likely focus on bolstering social justice and equality so that the world is more fair and peaceful for all.",
    "shortDescription": "You care a great deal for the well-being of all people and life. You likely also value diversity and protecting the environment.",
    "shortDescriptionShared": "You both care a great deal for the well-being of all people and life. You both likely also value diversity and protecting the environment."
  },
  "benevolence": {
    "id": "benevolence",
    "name": "benevolence",
    "description": "Being reliable and devoted to the needs of those around you gives you great satisfaction; you likely do a great deal to keep your close relationships thriving.",
    "descriptionShared": "Being reliable and devoted to the needs of those around you gives both of you great satisfaction; you both likely do a great deal to keep your close relationships thriving.",
    "shortDescription": "Forgiving, helping, and being loyal are important to you. You likely look to preserve and improve the lives of those that share your core interests or identities.",
    "shortDescriptionShared": "Forgiving, helping, and being loyal are important to each of you. You both likely look to preserve and improve the lives of those that share your core interests or identities."
  },
  "self_direction": {
    "id": "self_direction",
    "name": "self direction",
    "description": "At its essence, Self-Direction is a need for control, mastery, and independence - so it’s no surprise you might relish in choosing your own goals - and honing till they are just right. Likely curious, intelligent and a lover of freedom - you prefer to live by your own rules.",
    "descriptionShared": "At its essence, Self-Direction is a need for control, mastery, and independence - so it’s no surprise you both might relish in choosing your own goals - and honing till they are just right. Likely curious, intelligent and lovers of freedom - you both prefer to live by your own rules.",
    "shortDescription": "You value freedom of thought and action, preferring to come to conclusions or decisions yourself. You also likely draw great satisfaction when creating or exploring the world.",
    "shortDescriptionShared": "You both value freedom of thought and action, preferring to come to conclusions or decisions yourselves. Both of you also likely draw great satisfaction when creating or exploring the world."
  },
  "stimulation": {
    "id": "stimulation",
    "name": "stimulation",
    "description": "The world is a big place and you see the benefits of craving new experiences. On top of a need for variety and stimulation, you may also be a bit daring compared to most. You are likely a go-getter and change-maker at heart.",
    "descriptionShared": "The world is a big place and both of you see the benefits of craving new experiences. On top of a need for variety and stimulation, you both may also be a bit daring compared to most. You both are likely go-getters and change-makers at heart.",
    "shortDescription": "You highly value excitement, challenge, and positive change. Life is likely never dull with you around.",
    "shortDescriptionShared": "You both highly value excitement, challenge, and positive change. Life is likely never dull with either of you around."
  },
  "hedonism": {
    "id": "hedonism",
    "name": "hedonism",
    "description": "Whether through exploring the world or indulging in your favorite food, you likely love instant gratification and value decisions that reward your senses.",
    "descriptionShared": "Whether through exploring the world or indulging in your favorite foods, you both likely love instant gratification and value decisions that reward your senses.",
    "shortDescription": "Joy, pleasure and satisfaction are a big part of what drives you. From big moments to the little things, you find bliss in enjoying what you do.",
    "shortDescriptionShared": "Joy, pleasure and satisfaction are a big part of what drives you both. From big moments to the little things, you both find bliss in enjoying what you do."
  },
  "achievement": {
    "id": "achievement",
    "name": "achievement",
    "description": "Likely a perfectionist at heart, you strive to be the best you can be. And if you get recognition and approval in the process, that really is the cherry on top.",
    "descriptionShared": "Likely perfectionists at heart, you both strive to be the best you can be. And for both of you, if you get recognition and approval in the process, that really is the cherry on top.",
    "shortDescription": "Success - that’s a major goal for your life. Meeting your own standards of excellence is very important to you. It propels you forward.",
    "shortDescriptionShared": "Success - that’s a major goal for both your lives. Meeting your own standards of excellence is very important to you both. It propels each of you forward."
  },
  "power": {
    "id": "power",
    "name": "power",
    "description": "Power is invaluable. After all, it likely enables you to control the people and situations around you. When you're on top making the decision, you feel most yourself.",
    "descriptionShared": "Power is invaluable. After all, it likely enables you both to control the people and situations around you. For both of you, when you're on top making the decision, you feel most yourself.",
    "shortDescription": "Control freak? Maybe. But in your eyes it’s more about embracing power, holding dominance and getting the job done. You value social status and prestige.",
    "shortDescriptionShared": "Control freaks? Maybe. But for both of you it’s more about embracing power, holding dominance and getting the job done. You both value social status and prestige."
  },
  "security": {
    "id": "security",
    "name": "security",
    "description": "The sense of security that comes with feeling like you belong highly motivates you. Comfort for you is knowing the people and things you cherish are taken care of.",
    "descriptionShared": "The sense of security that comes with feeling like you belong highly motivates you both. Comfort for both of you is knowing the people and things you cherish are taken care of.",
    "shortDescription": "A feeling of safety, stability, and order is very important to you; this is true likely whether in society at large, at work, in your home, or in your relationships.",
    "shortDescriptionShared": "A feeling of safety, stability, and order is very important to you both; this is true likely whether in society at large, at work, in your homes, or in your relationships."
  }
}
